Repository liip/LiipImagineBundle, pull requests merged in 2018-03, with the labels that each got.

#1057 [CI] [CS] Add a required php-cs-fixer build run to Travis matrix
  .travis.yml
Labels: attn: minor, lvl: enhancement, stat: confirmed, type: cfg

#930 [Data Loader] [Data Locator] [Dependency Injection] Pass root paths to FileSystemLocator during construction
  Binary/Loader/FileSystemLoader.php
  Binary/Locator/FileSystemInsecureLocator.php
  Binary/Locator/FileSystemLocator.php
  Binary/Locator/LocatorInterface.php
  DependencyInjection/Factory/Loader/FileSystemLoaderFactory.php
  Resources/config/imagine.xml
  Tests/Binary/Loader/FileSystemLoaderTest.php
  Tests/Binary/Locator/AbstractFileSystemLocatorTest.php
  Tests/Binary/Locator/FileSystemInsecureLocatorTest.php
  Tests/Binary/Locator/FileSystemLocatorTest.php
  Tests/DependencyInjection/Factory/Loader/FileSystemLoaderFactoryTest.php
Labels: attn: bc break, lvl: enhancement, stat: confirmed, type: src

#1075 [Filters] [Post Processors] Remove configurable post processor interface for one interface and cleanup filter manager
  Imagine/Filter/FilterManager.php
  Imagine/Filter/PostProcessor/ConfigurablePostProcessorInterface.php
  Imagine/Filter/PostProcessor/JpegOptimPostProcessor.php
  Imagine/Filter/PostProcessor/MozJpegPostProcessor.php
  Imagine/Filter/PostProcessor/OptiPngPostProcessor.php
  Imagine/Filter/PostProcessor/PngquantPostProcessor.php
  Imagine/Filter/PostProcessor/PostProcessorInterface.php
  Tests/Imagine/Filter/FilterManagerTest.php
Labels: attn: bc break, attn: deprecation, stat: confirmed, type: src

#1077 [Documentation] [Meta] Update CHANGELOG.md and UPGRADE.md to reflect all merged changes
  CHANGELOG.md
  UPGRADE.md
Labels: attn: minor, stat: confirmed, type: doc

#1082 [Docs] Correct a tyop in the filters section of RST documentation
  README.md
Labels: attn: minor, stat: confirmed, type: doc

#1076 [Data Locator] Check if file is readable in file system loactor
  Binary/Locator/FileSystemLocator.php
Labels: attn: minor, lvl: enhancement, stat: confirmed, type: src
