Repository liip/LiipImagineBundle, pull requests merged in 2018-02, with the labels that each got.

#1046 [CS] Changes to support new php-cs-fixer rule set
  Async/ResolveCache.php
  Imagine/Cache/CacheManager.php
Labels: attn: minor, stat: confirmed, type: src

#1048 [CI] Move the "simple-phpunit install" command to Travis install section to collapse the output
  .travis.yml
Labels: attn: minor, lvl: enhancement, stat: confirmed, type: cfg, type: dep

#1040 [CS] Implement new php-cs-fixer rules and related code cleanup
  .gitignore
  .php_cs.dist
  Tests/Async/ResolveCacheProcessorTest.php
  Tests/DependencyInjection/Factory/Resolver/AwsS3ResolverFactoryTest.php
  Tests/DependencyInjection/LiipImagineExtensionTest.php
Labels: attn: minor, stat: reviewing, type: cfg

#1063 [Documentation] Correct indentation in AWS-S3 cache resolver documentation
  Resources/doc/cache-resolver/aws_s3.rst
Labels: attn: minor, stat: confirmed, type: doc

#1067 [Dependencies] Update imagine/imagine to ^0.7.1,<0.8
  composer.json
Labels: attn: minor, stat: confirmed, type: dep
